/*Banco de Dados: PostgreSQL*/

CREATE TABLE CLIENTE(
	ID_CLIENTE SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	
	UNIQUE(TELEFONE)
);

CREATE TABLE ENTREGADOR(
	ID_ENTREGADOR SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	
	UNIQUE(TELEFONE)
);

CREATE TABLE PRODUTO(
	ID_PRODUTO SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRECO DECIMAL(10,2) NOT NULL,
	TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE INGREDIENTE(
	ID_INGREDIENTE SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUTO_INGREDIENTE(
	ID_PRODUTO INT,
	ID_INGREDIENTE INT,
	
	CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
	CONSTRAINT FK_INGREDIENTE FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID_INGREDIENTE)
);

ALTER TABLE PRODUTO 
ADD COLUMN DESCRICAO VARCHAR(255);