/*Comandos SELECT*/

SELECT * 
FROM CLIENTE
ORDER BY NOME DESC;

SELECT * 
FROM PRODUTO
WHERE TIPO = 'Pizza'
ORDER BY NOME;

SELECT *
FROM INGREDIENTE;

SELECT *
FROM PRODUTO_INGREDIENTE;

SELECT
    PRODUTO.nome AS Nome_Produto,
    INGREDIENTE.nome AS Nome_Ingrediente
FROM
    PRODUTO
JOIN
    PRODUTO_INGREDIENTE ON PRODUTO.id_produto = PRODUTO_INGREDIENTE.id_produto
JOIN
    INGREDIENTE ON PRODUTO_INGREDIENTE.id_ingrediente = INGREDIENTE.id_ingrediente
WHERE
    PRODUTO.tipo = 'Pizza';